-- Importar sólo en tablas vacías. No contiene credenciales.;
START TRANSACTION;
INSERT INTO profile (id,name,role,description,tagline,location,avatar,cv,phone,show_phone) VALUES (1,'Silvia Agustina Banegas','Estudiante de Informática / Desarrolladora Web','Soy estudiante de informática, interesada en el desarrollo web, los sistemas y la creación de soluciones tecnológicas. Me gusta aprender nuevas herramientas, resolver problemas y participar en proyectos donde pueda combinar programación, diseño y organización.','Aprendiendo, creando y desarrollando una idea a la vez.','Mar del Plata, Buenos Aires, Argentina.','','','',false);
INSERT INTO experiences (title,organization,status,description,date,display_order) VALUES ('Desarrolladora Web - Prácticas Profesionalizantes','Grupo Núcleo','Actualidad','Participación en prácticas profesionalizantes orientadas al desarrollo de soluciones web para Grupo Núcleo, trabajando en proyectos reales y aplicando conocimientos de frontend, backend, bases de datos, APIs e integración de servicios.','',0);
INSERT INTO education (title,organization,description,location,status,date,display_order) VALUES ('Tecnicatura en Informática Personal y Profesional','EEST N°5 \"Amancio Williams\"','Estudiante de 7° año de la Tecnicatura en Informática Personal y Profesional.','Mar del Plata','En curso','',0);
INSERT INTO social_links (name,url,display_order) VALUES ('GitHub','https://github.com/BanegasAgustina',0);
INSERT INTO social_links (name,url,display_order) VALUES ('LinkedIn','https://www.linkedin.com/in/agustina-banegas-33418a370/',1);
INSERT INTO soft_skills (name,display_order) VALUES ('Autodidacta',0);
INSERT INTO soft_skills (name,display_order) VALUES ('Aprendizaje rápido',1);
INSERT INTO soft_skills (name,display_order) VALUES ('Organización',2);
INSERT INTO soft_skills (name,display_order) VALUES ('Responsabilidad',3);
INSERT INTO soft_skills (name,display_order) VALUES ('Proactividad',4);
INSERT INTO soft_skills (name,display_order) VALUES ('Adaptación',5);
INSERT INTO soft_skills (name,display_order) VALUES ('Trabajo en equipo',6);
INSERT INTO soft_skills (name,display_order) VALUES ('Resolución de problemas',7);
INSERT INTO soft_skills (name,display_order) VALUES ('Comunicación',8);
INSERT IGNORE INTO technologies(name) VALUES ('HTML');
INSERT IGNORE INTO skill_categories(name) VALUES ('Desarrollo web');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Estructura semántica de páginas web.','','',0 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='HTML' AND c.name='Desarrollo web';
INSERT IGNORE INTO technologies(name) VALUES ('CSS');
INSERT IGNORE INTO skill_categories(name) VALUES ('Desarrollo web');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Estilos, animaciones y diseños adaptables.','','',1 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='CSS' AND c.name='Desarrollo web';
INSERT IGNORE INTO technologies(name) VALUES ('JavaScript');
INSERT IGNORE INTO skill_categories(name) VALUES ('Desarrollo web');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Interactividad y lógica de aplicaciones web.','','',2 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='JavaScript' AND c.name='Desarrollo web';
INSERT IGNORE INTO technologies(name) VALUES ('React');
INSERT IGNORE INTO skill_categories(name) VALUES ('Desarrollo web');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Creación de interfaces web mediante componentes.','','',3 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='React' AND c.name='Desarrollo web';
INSERT IGNORE INTO technologies(name) VALUES ('Node.js');
INSERT IGNORE INTO skill_categories(name) VALUES ('Desarrollo web');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Desarrollo de servicios y aplicaciones de servidor.','','',4 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Node.js' AND c.name='Desarrollo web';
INSERT IGNORE INTO technologies(name) VALUES ('Express');
INSERT IGNORE INTO skill_categories(name) VALUES ('Desarrollo web');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Creación de rutas y APIs para aplicaciones web.','','',5 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Express' AND c.name='Desarrollo web';
INSERT IGNORE INTO technologies(name) VALUES ('Vite');
INSERT IGNORE INTO skill_categories(name) VALUES ('Desarrollo web');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Desarrollo y compilación de aplicaciones frontend.','','',6 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Vite' AND c.name='Desarrollo web';
INSERT IGNORE INTO technologies(name) VALUES ('MySQL');
INSERT IGNORE INTO skill_categories(name) VALUES ('Bases de datos');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Creación y administración de bases de datos relacionales.','','',7 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='MySQL' AND c.name='Bases de datos';
INSERT IGNORE INTO technologies(name) VALUES ('SQL');
INSERT IGNORE INTO skill_categories(name) VALUES ('Bases de datos');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Consultas y manipulación de datos relacionales.','','',8 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='SQL' AND c.name='Bases de datos';
INSERT IGNORE INTO technologies(name) VALUES ('Supabase');
INSERT IGNORE INTO skill_categories(name) VALUES ('Bases de datos');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Servicios de datos e integración para aplicaciones.','','',9 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Supabase' AND c.name='Bases de datos';
INSERT IGNORE INTO technologies(name) VALUES ('Git');
INSERT IGNORE INTO skill_categories(name) VALUES ('Control de versiones');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Control de versiones de proyectos.','','',10 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Git' AND c.name='Control de versiones';
INSERT IGNORE INTO technologies(name) VALUES ('GitHub');
INSERT IGNORE INTO skill_categories(name) VALUES ('Control de versiones');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Repositorios y colaboración en proyectos.','','',11 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='GitHub' AND c.name='Control de versiones';
INSERT IGNORE INTO technologies(name) VALUES ('Visual Studio Code');
INSERT IGNORE INTO skill_categories(name) VALUES ('Herramientas de desarrollo');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Edición y organización del código.','','',12 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Visual Studio Code' AND c.name='Herramientas de desarrollo';
INSERT IGNORE INTO technologies(name) VALUES ('XAMPP');
INSERT IGNORE INTO skill_categories(name) VALUES ('Herramientas de desarrollo');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Entornos de desarrollo local.','','',13 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='XAMPP' AND c.name='Herramientas de desarrollo';
INSERT IGNORE INTO technologies(name) VALUES ('Postman');
INSERT IGNORE INTO skill_categories(name) VALUES ('Herramientas de desarrollo');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Pruebas de endpoints y APIs.','','',14 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Postman' AND c.name='Herramientas de desarrollo';
INSERT IGNORE INTO technologies(name) VALUES ('Figma');
INSERT IGNORE INTO skill_categories(name) VALUES ('Herramientas de desarrollo');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Diseño de interfaces y prototipos.','','',15 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Figma' AND c.name='Herramientas de desarrollo';
INSERT IGNORE INTO technologies(name) VALUES ('Canva');
INSERT IGNORE INTO skill_categories(name) VALUES ('Herramientas de desarrollo');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Creación de recursos gráficos.','','',16 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Canva' AND c.name='Herramientas de desarrollo';
INSERT IGNORE INTO technologies(name) VALUES ('Windows');
INSERT IGNORE INTO skill_categories(name) VALUES ('Sistemas y soporte');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Uso y configuración del sistema operativo.','','',17 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Windows' AND c.name='Sistemas y soporte';
INSERT IGNORE INTO technologies(name) VALUES ('Linux básico');
INSERT IGNORE INTO skill_categories(name) VALUES ('Sistemas y soporte');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Uso básico del sistema operativo Linux.','','',18 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Linux básico' AND c.name='Sistemas y soporte';
INSERT IGNORE INTO technologies(name) VALUES ('Instalación de sistemas operativos');
INSERT IGNORE INTO skill_categories(name) VALUES ('Sistemas y soporte');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Instalación y puesta en marcha de sistemas.','','',19 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Instalación de sistemas operativos' AND c.name='Sistemas y soporte';
INSERT IGNORE INTO technologies(name) VALUES ('Configuración básica de programas');
INSERT IGNORE INTO skill_categories(name) VALUES ('Sistemas y soporte');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Instalación y configuración de programas.','','',20 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Configuración básica de programas' AND c.name='Sistemas y soporte';
INSERT IGNORE INTO technologies(name) VALUES ('Mantenimiento básico de PC');
INSERT IGNORE INTO skill_categories(name) VALUES ('Sistemas y soporte');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Tareas básicas de mantenimiento de computadoras.','','',21 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Mantenimiento básico de PC' AND c.name='Sistemas y soporte';
INSERT IGNORE INTO technologies(name) VALUES ('Formateo');
INSERT IGNORE INTO skill_categories(name) VALUES ('Sistemas y soporte');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Preparación y formateo de equipos.','','',22 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Formateo' AND c.name='Sistemas y soporte';
INSERT IGNORE INTO technologies(name) VALUES ('Limpieza de archivos');
INSERT IGNORE INTO skill_categories(name) VALUES ('Sistemas y soporte');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Organización y limpieza de archivos.','','',23 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Limpieza de archivos' AND c.name='Sistemas y soporte';
INSERT IGNORE INTO technologies(name) VALUES ('Soporte técnico básico');
INSERT IGNORE INTO skill_categories(name) VALUES ('Sistemas y soporte');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Asistencia básica en problemas de equipos y programas.','','',24 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Soporte técnico básico' AND c.name='Sistemas y soporte';
INSERT IGNORE INTO technologies(name) VALUES ('Microsoft Word');
INSERT IGNORE INTO skill_categories(name) VALUES ('Ofimática');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Redacción y formato de documentos.','','',25 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Microsoft Word' AND c.name='Ofimática';
INSERT IGNORE INTO technologies(name) VALUES ('Microsoft Excel');
INSERT IGNORE INTO skill_categories(name) VALUES ('Ofimática');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Organización de datos en hojas de cálculo.','','',26 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Microsoft Excel' AND c.name='Ofimática';
INSERT IGNORE INTO technologies(name) VALUES ('Microsoft PowerPoint');
INSERT IGNORE INTO skill_categories(name) VALUES ('Ofimática');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Creación de presentaciones.','','',27 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Microsoft PowerPoint' AND c.name='Ofimática';
INSERT IGNORE INTO technologies(name) VALUES ('Google Drive');
INSERT IGNORE INTO skill_categories(name) VALUES ('Herramientas online');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Organización y colaboración con archivos online.','','',28 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Google Drive' AND c.name='Herramientas online';
INSERT IGNORE INTO technologies(name) VALUES ('Correo electrónico');
INSERT IGNORE INTO skill_categories(name) VALUES ('Herramientas online');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Comunicación y organización del correo.','','',29 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Correo electrónico' AND c.name='Herramientas online';
INSERT IGNORE INTO technologies(name) VALUES ('Navegación web');
INSERT IGNORE INTO skill_categories(name) VALUES ('Herramientas online');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Búsqueda y consulta de información.','','',30 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Navegación web' AND c.name='Herramientas online';
INSERT IGNORE INTO technologies(name) VALUES ('Inteligencia Artificial');
INSERT IGNORE INTO skill_categories(name) VALUES ('Inteligencia artificial');
INSERT INTO skills(technology_id,category_id,description,level,icon,display_order) SELECT t.id,c.id,'Uso de herramientas de IA para desarrollo, generación de ideas, documentación, asistencia de programación y productividad.','','',31 FROM technologies t CROSS JOIN skill_categories c WHERE t.name='Inteligencia Artificial' AND c.name='Inteligencia artificial';
COMMIT;
