-- Ejecutar en SQL Editor de Supabase. No borra contenido existente.
begin;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
create table if not exists private.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table private.admin_users enable row level security;
revoke all on private.admin_users from public, anon, authenticated;
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from private.admin_users where user_id = (select auth.uid()));
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create or replace function public.valid_link(value text) returns boolean
language sql immutable set search_path = '' as $$
  select value = '' or (value ~ '^https?://[^[:space:]]+$');
$$;
create or replace function public.valid_image(value text) returns boolean
language sql immutable set search_path = '' as $$
  select value = '' or value ~ '^https://[^[:space:]]+$';
$$;
create table if not exists public.profile (
  id bigint primary key default 1 check (id = 1),
  name text not null check (length(name) between 2 and 160),
  role text not null check (length(role) between 2 and 200),
  description text not null check (length(description) between 10 and 6000),
  tagline text not null default '' check (length(tagline) <= 240),
  location text not null default '' check (length(location) <= 200),
  avatar text not null default '' check (public.valid_image(avatar)),
  cv text not null default '' check (public.valid_link(cv) or cv ~ '^/cv/[a-zA-Z0-9_-]+\.pdf$'),
  phone text not null default '' check (length(phone) <= 40),
  show_phone boolean not null default false,
  created_at timestamptz not null default now()
);
-- La tabla de perfil no se lee públicamente: el RPC elimina el teléfono oculto.
create or replace function public.get_public_profile() returns jsonb
language sql stable security definer set search_path = '' as $$
  select case when p.show_phone then to_jsonb(p) else to_jsonb(p) - 'phone' end
  from public.profile p where p.id = 1;
$$;
revoke all on function public.get_public_profile() from public;
grant execute on function public.get_public_profile() to anon, authenticated;
create or replace function public.save_profile(record jsonb) returns jsonb
language plpgsql security invoker set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Acceso no autorizado' using errcode = '42501'; end if;
  insert into public.profile(id,name,role,description,tagline,location,avatar,cv,phone,show_phone)
  values(1,record->>'name',record->>'role',record->>'description',coalesce(record->>'tagline',''),coalesce(record->>'location',''),coalesce(record->>'avatar',''),coalesce(record->>'cv',''),coalesce(record->>'phone',''),coalesce((record->>'show_phone')::boolean,false))
  on conflict(id) do update set name=excluded.name,role=excluded.role,description=excluded.description,tagline=excluded.tagline,location=excluded.location,avatar=excluded.avatar,cv=excluded.cv,phone=excluded.phone,show_phone=excluded.show_phone;
  return jsonb_build_object('id',1);
end;
$$;
revoke all on function public.save_profile(jsonb) from public;
grant execute on function public.save_profile(jsonb) to authenticated;

create table if not exists public.projects (
  id bigint generated by default as identity primary key check (id between 1 and 9007199254740991),
  title text not null check (length(title) between 2 and 200),
  description text not null check (length(description) between 2 and 6000),
  full_description text not null default '' check (length(full_description) <= 12000),
  technologies text[] not null default '{}' check (cardinality(technologies) <= 40),
  image text not null default '' check (public.valid_image(image)),
  category text not null check (category in ('Frontend','Backend','Full Stack','Diseño','Otros')),
  date text not null default '' check (length(date) <= 40),
  status text not null default '' check (length(status) <= 80),
  github text not null default '' check (public.valid_link(github)),
  demo text not null default '' check (public.valid_link(demo)),
  is_featured boolean not null default false,
  display_order integer not null default 0 check (display_order between 0 and 10000),
  created_at timestamptz not null default now()
);
create table if not exists public.skills (
  id bigint generated by default as identity primary key check (id between 1 and 9007199254740991),
  name text not null unique check (length(name) between 1 and 160),
  category text not null check (length(category) between 1 and 160),
  description text not null check (length(description) between 2 and 2000),
  level text not null default '' check (level in ('','Básico','Intermedio','Avanzado')),
  icon text not null default '' check (public.valid_image(icon)),
  display_order integer not null default 0 check (display_order between 0 and 10000),
  created_at timestamptz not null default now()
);
create table if not exists public.experiences (
  id bigint generated by default as identity primary key check (id between 1 and 9007199254740991),
  title text not null check (length(title) between 2 and 200),
  organization text not null check (length(organization) between 2 and 200),
  description text not null check (length(description) between 2 and 6000),
  date text not null default '' check (length(date) <= 40),
  status text not null default '' check (length(status) <= 80),
  display_order integer not null default 0 check (display_order between 0 and 10000),
  created_at timestamptz not null default now()
);
create table if not exists public.education (
  id bigint generated by default as identity primary key check (id between 1 and 9007199254740991),
  title text not null check (length(title) between 2 and 200),
  organization text not null check (length(organization) between 2 and 200),
  description text not null check (length(description) between 2 and 6000),
  location text not null default '' check (length(location) <= 200),
  date text not null default '' check (length(date) <= 40),
  status text not null default '' check (length(status) <= 80),
  display_order integer not null default 0 check (display_order between 0 and 10000),
  created_at timestamptz not null default now()
);
create table if not exists public.social_links (
  id bigint generated by default as identity primary key check (id between 1 and 9007199254740991),
  name text not null check (length(name) between 1 and 160),
  url text not null check (url <> '' and public.valid_link(url)),
  display_order integer not null default 0 check (display_order between 0 and 10000),
  created_at timestamptz not null default now()
);
create table if not exists public.soft_skills (
  id bigint generated by default as identity primary key check (id between 1 and 9007199254740991),
  name text not null check (length(name) between 2 and 160),
  display_order integer not null default 0 check (display_order between 0 and 10000),
  created_at timestamptz not null default now()
);
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (length(name) between 2 and 120),
  email text not null check (length(email) <= 254 and email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  subject text not null check (length(subject) between 3 and 160),
  message text not null check (length(message) between 10 and 6000),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
-- Grants mínimos y RLS para CADA tabla expuesta. Una cuenta registrada no es admin.
do $$
declare t text;
begin
  foreach t in array array['profile','projects','skills','experiences','education','social_links','soft_skills','contact_messages'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on public.%I from anon, authenticated',t);
    execute format('grant select,insert,update,delete on public.%I to authenticated',t);
    execute format('drop policy if exists admin_content on public.%I',t);
    execute format('create policy admin_content on public.%I for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))',t);
    if t not in ('profile','contact_messages') then
      execute format('grant select on public.%I to anon',t);
      execute format('drop policy if exists public_read on public.%I',t);
      execute format('create policy public_read on public.%I for select to anon,authenticated using (true)',t);
    end if;
  end loop;
end $$;
grant usage on schema public to anon,authenticated;
grant usage,select on all sequences in schema public to authenticated;
-- Sólo el backend opcional de contacto usa una clave secreta del servidor.
grant insert on public.contact_messages to service_role;
grant usage,select on sequence public.contact_messages_id_seq to service_role;
create index if not exists projects_order on public.projects(is_featured desc,display_order,id);
create index if not exists messages_date on public.contact_messages(created_at desc);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('portfolio-images','portfolio-images',true,5242880,array['image/png','image/jpeg','image/webp'])
on conflict(id) do update set public=true,file_size_limit=5242880,allowed_mime_types=excluded.allowed_mime_types;
-- storage.objects ya tiene RLS habilitado por Supabase.
drop policy if exists portfolio_image_read on storage.objects;
create policy portfolio_image_read on storage.objects for select to anon,authenticated using(bucket_id='portfolio-images');
drop policy if exists portfolio_image_insert on storage.objects;
create policy portfolio_image_insert on storage.objects for insert to authenticated
with check(bucket_id='portfolio-images' and (select public.is_admin()) and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists portfolio_image_update on storage.objects;
create policy portfolio_image_update on storage.objects for update to authenticated
using(bucket_id='portfolio-images' and (select public.is_admin()))
with check(bucket_id='portfolio-images' and (select public.is_admin()));
drop policy if exists portfolio_image_delete on storage.objects;
create policy portfolio_image_delete on storage.objects for delete to authenticated
using(bucket_id='portfolio-images' and (select public.is_admin()));
commit;
